[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
core_lib = { path = "../core_lib" }

[lib]
proc-macro = true
