[package]
name = "spp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "*"
toml = "*"
colored = "*"
glob = "*"
indicatif = "*"
delegation = { git = "https://github.com/arcane-rs/delegation", branch = "main" }
convert_case = "*"
proc_macros = { path = "../proc_macros" }
