[package]
name = "spp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "*"
toml = "*"
colored = "*"
glob = "*"
indicatif = "*"
enum_dispatch = "*"
convert_case = "*"
proc_macros = { path = "../proc_macros" }
